version: '3'
services:
  webhook:
    image: golang:1.14.1
    environment:
      GOPATH: ""
      GITHUB_TOKEN: "${GITHUB_TOKEN}"
    ports:
      - 8888:8888
    command: bash -c "go run server.go"
    volumes:
      - ../../:/go
